In [7]:
import numpy as np
np.arange(48).reshape(2,2,2,6)

array([[[[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11]],

        [[12, 13, 14, 15, 16, 17],
         [18, 19, 20, 21, 22, 23]]],


       [[[24, 25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34, 35]],

        [[36, 37, 38, 39, 40, 41],
         [42, 43, 44, 45, 46, 47]]]])

In [16]:
data = [[1,2,3,4],['a','b','c','d']]
data

[[1, 2, 3, 4], ['a', 'b', 'c', 'd']]

In [5]:
data1 = [[1,2,3,4],[5,6,7,8]]
data1

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [9]:
#generating array from existing data
arr1 = np.array(data1)
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
#printing array (will not show "array" as it shows in output
print(arr1)

[[1 2 3 4]
 [5 6 7 8]]


In [12]:
arr1.ndim

2

In [13]:
arr1.shape

(2, 4)

In [14]:
arr1.dtype

dtype('int64')

In [15]:
arr = np.array(data)
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])